config/routes.rb
Sandbox::Application.routes.draw do
  get "auth/facebook"

  root :to => 'Users#index'
  
  resources :users
  
  resource :session, :only => [:create, :destroy]

end

app/models/friend.rb
class Friend < ActiveRecord::Base
  attr_accessible :facebook_id, :location, :name
  
  acts_as_gmappable

  def gmaps4rails_address
    self.location
  end
  
  def gmaps4rails_infowindow
    "<img src='https://graph.facebook.com/#{self.facebook_id}/picture'>
     <p>#{self.name}</p>"
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :email, :facebook_access_token, :facebook_id, :location, :name, :password, :password_confirmation
  
  has_secure_password
  validates_uniqueness_of :email
  
  has_many :friends
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  
  helper_method :logged_in?, :current_user
  
  def logged_in?
    session[:user_id].present? && current_user.present?
  end
  
  def current_user
    User.find_by_id(session[:user_id])
  end
end

app/controllers/auth_controller.rb
require 'open-uri'

class AuthController < ApplicationController
  def facebook
    my_redirect_uri = "http://localhost:3000/auth/facebook"
    my_app_id = ""
    my_app_secret = ""
    users_code = params[:code]
    
    uri = "https://graph.facebook.com/oauth/access_token?client_id=#{my_app_id}&redirect_uri=#{my_redirect_uri}&client_secret=#{my_app_secret}&code=#{users_code}"
    
    response = open(uri).read
    
    token = response.split("&").first.split("=").last
    
    user = User.find(session[:user_id])
    user.facebook_access_token = token
    user.save
    
    if user.facebook_access_token
      friends_url = "https://graph.facebook.com/me/friends?fields=name,location&access_token=#{user.facebook_access_token}"
      response = open(friends_url).read
      json = JSON.parse(response)
      friends = json["data"]
      friends.each do |friend|
        if friend["location"] && friend["location"]["name"]
          user.friends.create name: friend["name"], location: friend["location"]["name"], facebook_id: friend["id"]
        end
      end
    end
    
    redirect_to user
  end
end

app/controllers/friends_controller.rb
class FriendsController < ApplicationController
  # GET /friends
  # GET /friends.json
  def index
    @friends = Friend.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @friends }
    end
  end

  # GET /friends/1
  # GET /friends/1.json
  def show
    @friend = Friend.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @friend }
    end
  end

  # GET /friends/new
  # GET /friends/new.json
  def new
    @friend = Friend.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @friend }
    end
  end

  # GET /friends/1/edit
  def edit
    @friend = Friend.find(params[:id])
  end

  # POST /friends
  # POST /friends.json
  def create
    @friend = Friend.new(params[:friend])

    respond_to do |format|
      if @friend.save
        format.html { redirect_to @friend, notice: 'Friend was successfully created.' }
        format.json { render json: @friend, status: :created, location: @friend }
      else
        format.html { render action: "new" }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /friends/1
  # PUT /friends/1.json
  def update
    @friend = Friend.find(params[:id])

    respond_to do |format|
      if @friend.update_attributes(params[:friend])
        format.html { redirect_to @friend, notice: 'Friend was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /friends/1
  # DELETE /friends/1.json
  def destroy
    @friend = Friend.find(params[:id])
    @friend.destroy

    respond_to do |format|
      format.html { redirect_to friends_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    if (user = User.find_by_email(params[:email])) && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to user, :notice => "Sign-in successful."
    else
      redirect_to root_url, :notice => "Sign-in unsuccessful."
    end
  end
  
  def destroy
    reset_session
    redirect_to root_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :require_login, :only => [:show, :edit, :update, :delete]
  
  def require_login
    if session[:user_id] && session[:user_id] == params[:id].to_i
      @user = current_user   
    else
      redirect_to root_url, :notice => "Not authorized for that."
    end
  end
  
  def root
    if logged_in?
      @user = current_user
      render 'show'
    else
      @users = User.all
      render 'index'
    end
  end

  def index
    @users = User.all
  end

  def show
    @my_app_id = ""
    @friends = @user.friends
    @json = @friends.to_gmaps4rails
  end

  def new
    @user = User.new
  end

  def edit
  end

  def create
    @user = User.new(params[:user])

    if @user.save
      session[:user_id] = @user.id
      redirect_to @user, notice: 'Sign-up successful.'
    else
      render 'new'
    end
  end

  def update
    if @user.update_attributes(params[:user])
      redirect_to @user, notice: 'Update successful.'
    else
      render 'edit'
    end
  end

  def destroy
    @user.destroy

    redirect_to users_url
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/auth_helper.rb
module AuthHelper
end

app/helpers/friends_helper.rb
module FriendsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/friends/_form.html.erb
<%= form_for(@friend) do |f| %>
  <% if @friend.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@friend.errors.count, "error") %> prohibited this friend from being saved:</h2>

      <ul>
      <% @friend.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :location %><br />
    <%= f.text_field :location %>
  </div>
  <div class="field">
    <%= f.label :facebook_id %><br />
    <%= f.text_field :facebook_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/friends/edit.html.erb
<h1>Editing friend</h1>

<%= render 'form' %>

<%= link_to 'Show', @friend %> |
<%= link_to 'Back', friends_path %>

app/views/friends/index.html.erb
<h1>Listing friends</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Location</th>
    <th>Facebook</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @friends.each do |friend| %>
  <tr>
    <td><%= friend.name %></td>
    <td><%= friend.location %></td>
    <td><%= friend.facebook_id %></td>
    <td><%= link_to 'Show', friend %></td>
    <td><%= link_to 'Edit', edit_friend_path(friend) %></td>
    <td><%= link_to 'Destroy', friend, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Friend', new_friend_path %>

app/views/friends/new.html.erb
<h1>New friend</h1>

<%= render 'form' %>

<%= link_to 'Back', friends_path %>

app/views/friends/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @friend.name %>
</p>

<p>
  <b>Location:</b>
  <%= @friend.location %>
</p>

<p>
  <b>Facebook:</b>
  <%= @friend.facebook_id %>
</p>


<%= link_to 'Edit', edit_friend_path(@friend) %> |
<%= link_to 'Back', friends_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Sandbox" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <link href="images/favicon.ico" rel="shortcut icon">
    <link href="images/apple-touch-icon.png" rel="apple-touch-icon">
    <link href="images/apple-touch-icon-72x72.png" rel="apple-touch-icon" sizes="72x72">
    <link href="images/apple-touch-icon-114x114.png" rel="apple-touch-icon" sizes="114x114">
    <link href='http://fonts.googleapis.com/css?family=IM+Fell+DW+Pica:400,400italic' rel='stylesheet' type='text/css'>
  </head>
  <body>
    <div class="container-fluid">
      <div class="row-fluid">
        <h1><%= link_to "Sandbox", root_url %></h1>
      </div><!--/row-->
      <div class="row-fluid">
        <% if logged_in? %>
          <%= link_to "Sign Out", session_url, :method => 'delete' %>
        <% else %>
          <%= link_to "Sign Up", new_user_url %> or Sign In:
          <%= form_tag session_url do %>
            <%= text_field_tag :email %>
            <%= password_field_tag :password %>
            <%= submit_tag "Sign In" %>
          <% end %>
        <% end %>
      </div><!--/row-->
      <div class="row-fluid">
        <div class="span9">
          <p><%= notice %></p>
          <%= yield %>
        </div>
      </div><!--/row-->
    </div> <!-- /container -->

    <!-- Javascripts
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "application" %>
    <%= yield :scripts %>

  </body>
</html>

app/views/users/_form.html.erb
<%= form_for @user, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :email, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :email, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :password, :class => 'control-label' %>
    <div class="controls">
      <%= f.password_field :password, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :password_confirmation, :class => 'control-label' %>
    <div class="controls">
      <%= f.password_field :password_confirmation, :class => 'text_field' %>
    </div>
  </div>
  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                users_path, :class => 'btn' %>
  </div>
<% end %>

app/views/users/edit.html.erb
<%- model_class = @user.class -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human,
                                   :default => "Edit #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/users/index.html.erb
<%- model_class = User.new.class -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:email) %></th>
      <th><%= model_class.human_attribute_name(:facebook_id) %></th>
      <th><%= model_class.human_attribute_name(:facebook_access_token) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:location) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= link_to user.email, user %></td>
        <td><%= user.facebook_id %></td>
        <td><%= user.facebook_access_token %></td>
        <td><%= user.name %></td>
        <td><%= user.location %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_user_path(user), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      user_path(user),
                      :method => :delete,
                      :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')),
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_user_path,
            :class => 'btn btn-primary' %>

app/views/users/new.html.erb
<%- model_class = @user.class -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human,
                                 :default => "New #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/users/show.html.erb
<div class="page-header">
  <h1>User</h1>
</div>

<%= link_to "Click here to Authorize Facebook", "https://www.facebook.com/dialog/oauth?client_id=#{@my_app_id}&redirect_uri=http://localhost:3000/auth/facebook&state=SOME_ARBITRARY_BUT_UNIQUE_STRING&scope=friends_location" %>

<dl class="dl-horizontal">
<p><strong>Email:</strong> <%= @user.email %></p>
<p><strong>Name:</strong> <%= @user.name %></p>
<p><strong>Location:</strong> <%= @user.location %></p>

<%= gmaps(markers: { data: @json, options: { do_clustering: true, randomize: true, max_random_distance: 10000 } }) %>

<ul>
<% @friends.each do |friend| %>
  <li><%= friend.name %> is from <%= friend.location %></li>
<% end %>
</ul>